providers = ['node']
buildImage = 'ghcr.io/railwayapp/nixpacks:ubuntu-1745544451'

[variables]
CI = 'true'
NIXPACKS_METADATA = 'node'
NODE_ENV = 'production'
NPM_CONFIG_PRODUCTION = 'false'

[phases.build]
dependsOn = ['install']
cmds = ['bun run build']
cacheDirectories = ['node_modules/.cache']

[phases.install]
dependsOn = ['setup']
cmds = ['bun i --no-save']
cacheDirectories = ['/root/.bun']
paths = ['/app/node_modules/.bin']

[phases.setup]
nixPkgs = ['nodejs_20', 'bun']
nixOverlays = [
    'https://github.com/railwayapp/nix-npm-overlay/archive/main.tar.gz',
]
nixpkgsArchive = 'f69ae4816bc1b501460ad2c0c63ed0cc4a9b876e'

[start]
cmd = 'bun run start'
